services:
  - type: web
    name: apps
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn academy_test.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
